
export const projects = [
  {
    id: '1',
    name: 'Multi-Post Stories Gain+Glory I Love you !',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
  {
    id: '2',
    name: 'Multi-Post Stories Gain+Glory',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
  {
    id: '3',
    name: 'Multi-Post Stories Gain+Glory',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
  {
    id: '4',
    name: 'Multi-Post Stories Gain+Glory',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
  {
    id: '5',
    name: 'Multi-Post Stories Gain+Glory',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
  {
    id: '6',
    name: 'Multi-Post Stories Gain+Glory',
    technologies: ['Ruby on rails', 'css', 'Javascript', 'html'],
    desktopPopupTech: [
      'Codekit',
      'Github',
      'Javascript',
      'Bootstrap',
      'Terminal',
      'Codepen',
    ],
    mobilePopupTech: ['Ruby on rails', 'css', 'javascript'],
    title: 'Keeping track of hundreds of components',
    popUpImageDesktop: 'assets/images/snapshot-desktop.png',
    popUpImageMobile: 'assets/images/snapshoot-portfolio.png',
  },
];